### ISSUE TITLE
[PE-D][Tester D] Adding a pet with only health without other tags will result in the program to exit unexpectedly

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-2/tp#151]
**Issue**

As seen below, when I tried to add a pet with only its health, the program does not catch the error in tags given and cause me to exit unexpectedly. 

**Suggestion**

Suggestion is to check for all present tags. 

**Output**

![2022-10-28 (2).png](https://raw.githubusercontent.com/chydarren/ped/main/files/29966cc5-be43-43ed-b623-474bcbdb1768.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: chydarren/ped#2

**Comment by zheqis12138** [comment]
<img width="600" alt="Screen Shot 2022-11-01 at 15 43 09" src="https://user-images.githubusercontent.com/88580183/199183725-f005a804-91cc-4ed8-89ff-f5dc5ab62476.png">
