### ISSUE TITLE
[PE-D][Tester A] Skipping index in view after removing a pet and adding more pets

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-2/tp#159]
![image.png](https://raw.githubusercontent.com/Brandon-OS/ped/main/files/fcbcdbb2-b095-48c0-854e-ef8946b3e218.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Brandon-OS/ped#2

**Comment by zheqis12138** [comment]
It is how we design the id
