### ISSUE TITLE
[PE-D][Tester A] Jumping index when removing and adding services

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-2/tp#162]
![image.png](https://raw.githubusercontent.com/Brandon-OS/ped/main/files/9c93e39c-1763-4519-9fa2-e917ea7f04b3.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Brandon-OS/ped#3

**Comment by sylviahe171** [comment]
Indexes are absolute index that will not change even after some items are deleted. Will add this explanation to UG
