### ISSUE TITLE
[PE-D][Tester A] Skipping index in employee view

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-2/tp#169]
![image.png](https://raw.githubusercontent.com/Brandon-OS/ped/main/files/c8fa1f22-e82b-4f1c-9e5e-fe6dc7fcae03.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Brandon-OS/ped#6

**Comment by Yikai-Cao** [comment]
solved
