### ISSUE TITLE
[PE-D][Tester B] Wrong index in tasks added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-2/tp#174]
After the two failed to add of tasks in `#3`, i successfully added a task, which is indexed wrongly and `task finish` fails from wrong index

This issue seem to arise when some failed attempt of adding `task` still occupies a place in the list of `task`, and all valid addition of `task` is placed after the ''phantom entries".
To recify the issue, check what happen if an invalid `task` is accpeted from the input. Are they put into `task` list? 
![Screenshot 2022-10-28 at 5.01.48 PM.png](https://raw.githubusercontent.com/Brominne/ped/main/files/df9784a7-0607-41c6-99df-84289a039bf5.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Brominne/ped#4

**Comment by yongjicode** [comment]
bro if u 'task finish i/3' it wouldve been finished, u should be following what is displayed????? why u assuming its index??? it say task 3 means its 3, u 'finish i/1' why would task 3 be finished bruh seriously
