### ISSUE TITLE
[PE-D][Tester C] service add: empty description

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-2/tp#181]
Service add command does not handle exception when the service description is empty 

![image.png](https://raw.githubusercontent.com/bdthanh/ped/main/files/a345a262-b1f3-4350-8325-20d64986bfd0.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: bdthanh/ped#8

**Comment by sylviahe171** [comment]
solved
