### ISSUE TITLE
[PE-D][Tester C] service remove: error doesn't print out

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-2/tp#184]
When I remove service with index out of range, there is no error message printed

![image.png](https://raw.githubusercontent.com/bdthanh/ped/main/files/6b8d35d4-8613-49da-a5b4-84881c32e5c0.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: bdthanh/ped#9

**Comment by sylviahe171** [comment]
fixed
