### ISSUE TITLE
[PE-D][Tester B] Add pet crash program

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-2/tp#186]
The missing number after field of `h/` in the command `pet add n/name s/specie h/number` crashes the software

This seems to be an unhandled parsing error in the field `h/`
![Screenshot 2022-10-28 at 5.06.47 PM.png](https://raw.githubusercontent.com/Brominne/ped/main/files/335063e4-c8b0-4c78-961f-a56c27798d0d.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Brominne/ped#6

**Comment by zheqis12138** [comment]
<img width="506" alt="Screen Shot 2022-11-01 at 15 09 17" src="https://user-images.githubusercontent.com/88580183/199178443-57ba9726-b726-4621-ac45-d88f0f4a913f.png">
