### ISSUE TITLE
[PE-D][Tester C] Storage 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-2/tp#188]
There is no storage for user to store their data, so it is impractical. Since user has a clinic and has patients in different days, so this app should able to store the data. Therefore, once user runs your app, they cannot close it, otherwise, all data is gone

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: bdthanh/ped#10

**Comment by sylviahe171** [comment]
This feature will be added in the future
