### ISSUE TITLE
[PE-D][Tester D] Two error messages returned for the finishing of task that does not exist 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-2/tp#195]
**Issue**

I think the team might have accidentally caused the command to return two error messages. I believe the first one was intended, whereas the second one should not appear even though there is some form of relevance to the first message. 

**Suggestion**

Be clear with the error message to return upon handling each error to avoid doubts and confusion for the user.

**Output**

![2022-10-28 (19).png](https://raw.githubusercontent.com/chydarren/ped/main/files/b6d84027-4792-4ec2-8588-fabac91dc0f7.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: chydarren/ped#13

**Comment by yongjicode** [comment]
fixed
