### ISSUE TITLE
[PE-D][Tester C] UG command summary 

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-2/tp#205]
typo in command sumary 

![image.png](https://raw.githubusercontent.com/bdthanh/ped/main/files/cca10873-5ec0-454c-8032-4f4e5a12e87d.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: bdthanh/ped#19

**Comment by sylviahe171** [comment]
fixed

**Comment by sylviahe171** [comment]
Summary is spelled correctly
