### ISSUE TITLE
Code Review: @nvknow

### ISSUE THREAD

**Issue by mathanmahe** [AY2223S1-CS2113-F11-2/tp#228]
@nvknow 
**src/main/java/pet/Pet.java**
![image](https://user-images.githubusercontent.com/77711860/198910839-f92a0f07-c680-4556-bc8a-3e28eef7e1a7.png)
![image](https://user-images.githubusercontent.com/77711860/198911834-7e09a9e6-2f00-48f0-bfcf-16ccbea048df.png)

1. Line 8: Consider using a more meaningul variable name, as currently the difference between id and petId might not be clear. Can use sth like `idCounter` instead of `id`.
2. Line 84: Use the default branch. Can raise a suitable error message to indicate that this position should not be reached.

**src/main/java/ui/Ui.java**
![image](https://user-images.githubusercontent.com/77711860/198911005-f87aca35-e8ee-4894-b83c-9e0b6073792d.png)
1. Avoid using magic strings, and consider using named constants to represent messages that are not likely to change like `LOGO`, `LINE_DIVIDER` ,etc, as this will improve readability

**src/main/java/parser/TaskParser.java** 
![image](https://user-images.githubusercontent.com/77711860/198912020-5596c70d-dcea-4731-880a-525274b7dec4.png)

1. In general try to avoid magic strings and consider abstracting them into named constant messages.
2. Line 111: Name well - startofI could trip up the reader as `i` could refer to multiple things in programming. Can consider renaming `/i` as INPUT_FLAG constant and `startofI` as `startIndexofInputFlag` variable.

**src/main/java/parser/ServiceParser.java**
![image](https://user-images.githubusercontent.com/77711860/198911409-04c56b53-7e1b-488f-a863-09d0c293fe88.png)
1. Lines 20-40 - Make the happy path prominent - Code Quality Guideline
2. Lines 20-40 - Avoid arrowhead code caused by deep nesting

**Comment by Yikai-Cao** [comment]
Thanks for your suggestion. All the issues have been solved.
