### ISSUE TITLE
Code Review: @yongjicode

### ISSUE THREAD

**Issue by mathanmahe** [AY2223S1-CS2113-F11-2/tp#229]
@yongjicode

src/main/java/task/TaskList.java 
![image](https://user-images.githubusercontent.com/77711860/198919110-dd845a81-f074-412c-881e-c388c62e96de.png)
1. Lines 31,37: Consider writing comments to the reader
2. Line 16: Comment minimally but sufficiently: avoid comments for self explanatory code.
3. Line 20: Avoid using magic strings. Consider using a named constant like `LINE_DIVIDER`
4. Line 56: Consider writing as a javadoc comment. Additionally consider writing javadoc comments for all public methods.
5. Line 67: Avoid complicated expressions. Consider breaking down into intermediate variables for better readability.

src/main/java/appointment/Appointment.java 
![image](https://user-images.githubusercontent.com/77711860/198919939-5fe6787e-c3d3-41c5-a0e2-8a57bcffa63b.png)

1. Line 35: Consider writing as a javadoc comment.
2. Line 39: Avoid using magic strings

**Comment by yongjicode** [comment]
Added comments for public functions and fixed magic strings
